[default.extend-words]
Rela = "Rela"
eles = "eles"
delink = "delink"
testng = "testng"
ba = "ba"
referer = "referer"
keynode = "keynode"
SCHEM = "SCHEM"
wheres = "wheres"
Wheres = "Wheres"
Parenthesed = "Parenthesed"
pogress = "pogress"
Pogress = "Pogress"
yoy = "yoy"
YOY = "YOY"
Leafs = "Leafs"
leafs = "leafs"
hiden = "hiden"

[files]
extend-exclude = [
    "public/",
    "amap-wx/",
    "m-icon/",
    "uni-card/",
    "uni-col/",
    "uni-link/",
    "uni-list/",
    "uni-list-item/",
    "uni-row/",
    "migration/",
    "mapFiles/",
    "core/frontend/src/views/chart/components/table/TableNormal.vue",
    "core/backend/src/main/java/io/dataease/ext/ExtSysUserMapper.xml",
    "core/backend/src/main/java/io/dataease/ext/AuthMapper.xml",
    "core/backend/src/main/java/io/dataease/ext/ExtAuthMapper.xml",
    "installer/dataease/templates/be.conf"
]

