version: '2.1'
services:

  dataease:
    image: registry.cn-qingdao.aliyuncs.com/dataease/dataease2.0:DE_TAG
    container_name: dataease
    ports:
      - ${DE_PORT}:8100
    volumes:
      - ${DE_BASE}/dataease2.0/conf:/opt/apps/config
      - ${DE_BASE}/dataease2.0/logs/dataease:/opt/dataease2.0/log
      - ${DE_BASE}/dataease2.0/data/static-resource:/opt/dataease2.0/data/static-resource
      - ${DE_BASE}/dataease2.0/data/map:/opt/dataease2.0/data/map
      - ${DE_BASE}/dataease2.0/cache:/opt/dataease2.0/cache
    depends_on:
      DE_MYSQL_HOST:
        condition: service_healthy
    networks:
      - dataease-network

networks:
  dataease-network: