server:
  max-http-request-header-size: 100MB
  tomcat:
    connection-timeout: 70000
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://${DE_MYSQL_HOST}:${DE_MYSQL_PORT}/${DE_MYSQL_DB}?${DE_MYSQL_PARAMS}
    username: ${DE_MYSQL_USER}
    password: ${DE_MYSQL_PASSWORD}
dataease:
  origin-list: localhost:8080,localhost:8100,localhost:9080