
spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/opt/dataease2.0/desktop;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;MODE=MySQL
    username: sa
    password: 123456

  h2:
    console:
      enabled: true
      path: /h2-console
  messages:
    basename: i18n/core
  flyway:
    enabled: true
    table: de_desktop_version
    validate-on-migrate: false
    locations: classpath:db/desktop
    baseline-on-migrate: true
    out-of-order: true

mybatis-plus:
  mapper-locations: classpath:mybatis/*.xml
